### ISSUE TITLE
More language support

### ISSUE THREAD

**Issue by ghost** [tomsik68/vim-crystallite#3]
Hi, I would love to see this vim colorschemes supports in the future:
- Ruby
- Dlang
- Golang
- Groovy
- Scala
- Clojure
- C#

These languages are not as popular as C++/C, but on Linux, the usage are reasonable enough. Anyway, the current colorscheme looks fluid on the eye.

**Comment by tomsik68** [comment]
Hi, thanks for the feedback. I'm glad you like the colorscheme :)
While adding languages, I'm trying my best for them to fit in the scheme, so I use my understanding of the programming language to recognize what is supposed to stand out in given context.
I'm writing this, because I don't currently know Clojure and Scala, so I'm not be able to add them at the moment.

**Comment by ghost** [comment]
Hi, thanks for the reply. I'll try to add more languages support (maybe) after I familiarize myself with viml.

**Comment by tomsik68** [comment]
There's a neat trick that helps with adding new highlight elements. 
If you add this snippet to your vimrc, you'll be able to see the "name" of element in code after pressing `CTRL-p`.

```
nmap <C-S-P> :call <SID>SynStack()<CR>
function! <SID>SynStack()
    if exists("*synstack")
        echo map(synstack(line('.'), col('.')), 'synIDattr(v:val, "name")')
    endif
endfunc
```

Then, you can follow this neat chart: http://www.calmar.ws/vim/256-xterm-24bit-rgb-color-chart.html or just use existing colors to find the desired color. Say you found element called `rustIdentifier`. To highlight it with color `46 #00ff00` (from the chart) and **bold**, use the following line:
`hi rustIdentifier ctermfg=46 guifg=#00ff00 cterm=BOLD`.

**Comment by ghost** [comment]
Alright thanks!
